### ISSUE TITLE
(tlg0003-trans) adding new translations of Thucydides and adding the books 5-8 of Zevort (opp-fre1)

### ISSUE THREAD

**Issue by gregorycrane** [PerseusDL/canonical-greekLit#1473]
This pull request does two things.

1. It adds the remaining books of Zevort's French translation (we only had volume 1 with books 1-4). 

2. It adds a number of translations that have languished for up to 15 years.  This is a big step.

3. I have used my own automatic tests to check the XML. Whatever I missed, I will add to those checks if possible.

4. As always, I made sure these pass hooktest on my machine before the pull request.

# earlier notes below

I am finally going to add to Thuc translations that have sat for years. A number of translations have been posted in Scaife but we have more that have been languishing.

I need URNs for. Some may be in the online catalog but  I don't know if they are what we want to use now.

- English: Charles Foster Smith (Loeb): https://catalog.hathitrust.org/Record/006786442?

- English: Henry Dale (1849): https://hdl.handle.net/2027/uiug.30112004593338
- French: Elie-Ami Bétant (1863): https://github.com/OpenGreekAndLatin/french_trans-dev/blob/master/thucydides_1863.xml
- French: Zevort (1869): https://github.com/OpenGreekAndLatin/french_trans-dev/blob/master/thucydides_1_1869.xml
- - NB: This is the second volume of Zevort. It looks like we only have volume one in Scaife: https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0003.tlg001.opp-fre1:front.1/. We don't need a URN for this -- I include it so that adding vol2 does not slip by!

- Latin: Lorenzo Valla (1564 edition/printing): https://polovea.sebina.it/SebinaOpac/resource/thucydides-laurentio-valla-interprete-nunc-postremo-correctus-ex-graeco-innumeris-locis-emendatus-qu/VEA2445988?locale=eng
- Latin: Friedrich Haase (Didot 1869): https://catalog.hathitrust.org/Record/008650607

- German: Gürsching 1856: https://catalog.hathitrust.org/Record/008923830

- Italian: Translator not listed (Florence 1835): https://catalog.hathitrust.org/Record/008643486

**Comment by AlisonBabeu** [comment]
Hi @gregorycrane , so we have been in the habit of creating new URNs for editions using 1st1K or OGL depending on the text and the collection, unless it is an updated Perseus edition. A number of these do have URNs in the catalog, but a number may be invalid due to the inability to update the metadata or the interface for so long. I’ve also long wanted to revisit renumbering all of the Thucydides URNS, since they don’t make logical sense (lat17, may be 1 of 4 Latin editions), but that is for another issue and another conversation. 

So I'd use as follow:

- tlg0003.tlg001.1st1K-eng1
- tlg0003.tlg001.1st1K-eng2
- tlg0003.tlg001.1st1K-fre1
- tlg0003.tlg001.opp-fre1 (want a reminder to update the metadata when the file is updated), alternatively when the additional text is added we could just renumber this tlg0003.tlg001.1st1K-fre2
- tlg0003.tlg001.1st1K-lat1
- tlg0003.tlg001.1st1K-lat2
- tlg0003.tlg001.1st1K-ger1 (I'm planning to update the other URNs to 1st1K-ger2 and ger3 respectively when this work is done). 
- tlg0003.tlg001.1st1K-ita1

**Comment by gregorycrane** [comment]
I really really don't want to create a new folder in First1KGreek for Thuc -- there is no tlg0003 now. I want to keep these in canonical-greekLit, even if we use those URNs.

**Comment by lcerrato** [comment]
Did you want to mint URNs with "perseus" in them? This folder already contains files without "perseus" in the name. I don't think we restrict the naming practice based on repo location.

**Comment by AlisonBabeu** [comment]
We don't and of course there is no reason we could not just give these Perseus URNs of course (I'm not into simple solutions today!)

**Comment by gregorycrane** [comment]
I found another German translation: It looks like ger4 is still free and I will use that if I don't hear otherwise.

         <monogr>
            <title>Die Rede des Perikles für die Gefallenen</title>
            <author>Thucydides</author>
            <respStmt>
              <name>Rudolf G. Binding</name>
              <resp>translator</resp>
            </respStmt>
            <imprint>
              <pubPlace>Mainz-Kastel</pubPlace>
              <publisher>Hanns Marxen</publisher>
              <date>1937</date>

**Comment by lcerrato** [comment]
Was this fixed? I see several PRs referencing it

**Comment by AlisonBabeu** [comment]
hi @lcerrato yes I edited all the Thucydides files and changed some of the URNs. I believe all of the Thucydides files should be correct and complete (as far as that goes)
