### ISSUE TITLE
<l/> without @n 

### ISSUE THREAD

**Issue by gcelano** [PerseusDL/canonical-greekLit#371]
The following texts present only some lines <l/> with @n (while all of them numbered would be ideal):

urn:cts:greekLit:tlg0001.tlg001.perseus-grc2
urn:cts:greekLit:tlg0006.tlg017.perseus-grc2
urn:cts:greekLit:tlg0011.tlg004.perseus-grc2
urn:cts:greekLit:tlg0013.tlg003.perseus-grc2
urn:cts:greekLit:tlg0013.tlg004.perseus-grc2
urn:cts:greekLit:tlg0013.tlg005.perseus-grc2
urn:cts:greekLit:tlg0013.tlg006.perseus-grc2
urn:cts:greekLit:tlg0013.tlg007.perseus-grc2
urn:cts:greekLit:tlg0013.tlg008.perseus-grc2
urn:cts:greekLit:tlg0013.tlg009.perseus-grc2
urn:cts:greekLit:tlg0013.tlg010.perseus-grc2
urn:cts:greekLit:tlg0013.tlg011.perseus-grc2
urn:cts:greekLit:tlg0013.tlg012.perseus-grc2
urn:cts:greekLit:tlg0013.tlg013.perseus-grc2
urn:cts:greekLit:tlg0013.tlg014.perseus-grc2
urn:cts:greekLit:tlg0013.tlg015.perseus-grc2
urn:cts:greekLit:tlg0013.tlg016.perseus-grc2
urn:cts:greekLit:tlg0013.tlg017.perseus-grc2
urn:cts:greekLit:tlg0013.tlg018.perseus-grc2
urn:cts:greekLit:tlg0013.tlg019.perseus-grc2
urn:cts:greekLit:tlg0013.tlg020.perseus-grc2
urn:cts:greekLit:tlg0013.tlg021.perseus-grc2
urn:cts:greekLit:tlg0013.tlg022.perseus-grc2
urn:cts:greekLit:tlg0013.tlg023.perseus-grc2
urn:cts:greekLit:tlg0013.tlg024.perseus-grc2
urn:cts:greekLit:tlg0013.tlg025.perseus-grc2
urn:cts:greekLit:tlg0013.tlg026.perseus-grc2
urn:cts:greekLit:tlg0013.tlg027.perseus-grc2
urn:cts:greekLit:tlg0013.tlg028.perseus-grc2
urn:cts:greekLit:tlg0013.tlg029.perseus-grc2
urn:cts:greekLit:tlg0013.tlg030.perseus-grc2
urn:cts:greekLit:tlg0013.tlg031.perseus-grc2
urn:cts:greekLit:tlg0013.tlg032.perseus-grc2
urn:cts:greekLit:tlg0013.tlg033.perseus-grc2
urn:cts:greekLit:tlg0020.tlg002.perseus-grc2
urn:cts:greekLit:tlg0020.tlg003.perseus-grc2
urn:cts:greekLit:tlg0033.tlg001.perseus-grc2
urn:cts:greekLit:tlg0033.tlg002.perseus-grc2
urn:cts:greekLit:tlg0033.tlg003.perseus-grc2
urn:cts:greekLit:tlg0033.tlg004.perseus-grc2
urn:cts:greekLit:tlg0085.tlg004.perseus-grc2
urn:cts:greekLit:tlg0085.tlg006.perseus-grc2
urn:cts:greekLit:tlg0085.tlg007.perseus-grc2

**Comment by lcerrato** [comment]
Hi @gcelano 
I really can't prioritize everything but am working in batches based on author. I will have more student help this summer.

Are you sure about these? I just finished tlg0085 for instance. The Nemo display only displays every 5 lines but the markup shows all of them.

**Comment by gcelano** [comment]
I downloaded the repo a few days ago and the source XML files I mention above do not have @n in all </l>.  Unless you have changed something recently, it is sure they miss @n

**Comment by lcerrato** [comment]
All line numbers have been added to Aeschylus as of 12 days ago.

**Comment by gcelano** [comment]
You are right. Aeschylus seems ok now. Hence, only the other documents are missing.

**Comment by lcerrato** [comment]
@gcelano 
Let me know if there are still empty `<l>` tags lurking in this list and if not, please close this out.
Thanks!

**Comment by aurelberra** [comment]
Hello. I may comment on this issue because I recently had the same problem in Aristophanes while setting up a little Capitains/Nemo [project](https://classnum-mnemosyne.herokuapp.com/) with my students.

Adding all line numbers and/or de-duplicating them is tricky. I tried to automate the processes with scripts (partly mine, partly Thibault Clérice's XSLT), but ended up doing quite a lot of manual corrections to get all lines numbered and unique (adding "b", "c", or "d" as needed). I always made sure the numbering inferred from `milestone`s remained valid (e.g. `<milestone ed="p" n="54" unit="card"/>` comes right before `<l n="54">`). However, every line in between those milestones can be misnumbered due to the mid-line speaker changes. As I worked through some of the files, I made educated guesses, but the numbers should be checked against the original editions (which not infrequently split and number the verses in an idiosyncratic way).

With this caveat, I think we have improved the files. The following editions have all their lines numbered:

tlg0019/tlg001/tlg0019.tlg001.perseus-grc1.xml
tlg0019/tlg002/tlg0019.tlg002.perseus-grc1.xml
tlg0019/tlg003/tlg0019.tlg003.perseus-grc2.xml
tlg0019/tlg004/tlg0019.tlg004.perseus-grc1.xml
tlg0019/tlg006/tlg0019.tlg006.perseus-grc2.xml
tlg0019/tlg007/tlg0019.tlg007.perseus-grc1.xml
tlg0019/tlg010/tlg0019.tlg010.perseus-grc2.xml

In the other files the lines are still partially numbered:

tlg0019/tlg005/tlg0019.tlg005.perseus-grc1.xml
tlg0019/tlg008/tlg0019.tlg008.perseus-grc1.xml
tlg0019/tlg009/tlg0019.tlg009.perseus-grc2.xml
tlg0019/tlg011/tlg0019.tlg011.perseus-grc1.xml

The files can be found at <https://github.com/classnum/mnemosyne/tree/master/corpora/data/tlg0019>.

I would be happy to know if you have a better system to deal with this problem, and whether the files should be contributed.

**Comment by lcerrato** [comment]
@aurelberra Thank you!
I think we should move this to a dedicated issue as this is not the same problem as the original issue -- this is a result of the majority of the files not being converted yet and these being drama.
Since these are not migrated texts (except for Frogs) they will need other related conversion work aside from line numbering and a consistency check. (Nothing with a "grc1" ending is a converted file.)
I am currently working on documentation to assist with conversion work but will not be documenting drama right (I am focusing on better training sets for novice contributors). There are a lot of problems with inconsistent handling of all of the Perseus drama that require special attention.
I will add more information on a dedicated author/work issue.

**Comment by aurelberra** [comment]
Thanks for the explanations! I have to say I am not aware of the conversion policy. I should have asked about "grc1/lat1" vs "grc2/lat2". I guess our improved versions are partially ready for the "grc2/lat2" status. Please let me know how to proceed and if I can help!

**Comment by lcerrato** [comment]
closing original issue and moving end discussion to https://github.com/PerseusDL/canonical-greekLit/issues/497
