### ISSUE TITLE
(tlg0004.001) Epidoc and CTS coversion

### ISSUE THREAD

**Issue by charhoughton** [PerseusDL/canonical-greekLit#511]
Claiming this text group for conversion work

**Comment by charhoughton** [comment]
@lcerrato please bump the URNs for tlg0004.tlg001.perseus-eng1.xml and tlg0004.tlg001.perseus-grc1.xml. Thanks

**Comment by lcerrato** [comment]
@charhoughton Sure, please use 
tlg0004.tlg001.perseus-grc2 and tlg0004.tlg001.perseus-eng2

**Comment by charhoughton** [comment]
@lcerrato I have a question about how to copy a `<change>` over, which contains this  `<item>
$Log: dl_gk.xml,v $
Revision 1.2  2010-06-24 15:41:01  gcrane
edits to improve named entities

Revision 1.1  2009/12/09 18:06:43  rsingh04
moved more xml files around based on copyright status

Revision 1.1  2009/11/17 17:26:53  rsingh04
moved more texts around based on copyright status

Revision 1.8  2009/07/30 21:17:18  student
adding section numbers, putting foreign lang tags on footnotes - ad
Revision 1.7  2009/07/23 21:30:34  student
adding section numbers, putting foreign lang tags on footnotes - ad
Revision 1.6  2009/07/17 20:30:12  student
adding section numbers, putting foreign lang tags on footnotes - ad
Revision 1.5  2009/07/16 21:17:41  student
adding milestone numbers - ad
Revision 1.4  2009/07/02 22:04:55  student
adding section numbers, putting foreign lang tags on footnotes - ad
Revision 1.3  2009/06/26 18:34:00  student
adding section numbers, putting foreign lang tags on footnotes - ad
Revision 1.2  2009/06/24 21:29:53  student
adding section numbers, putting foreign lang tags on footnotes - ad
Revision 1.1  2009/06/22 20:56:42  rsingh04
beta code versions of diogenes, greek and english.  also combined the two volumes of each text (originally in incunabula/Diogenes[English|Greek][1|2].xml into one.  still need to add sections for citation support
</item>`
This is all attributed to a single `<change>,` and I'm not sure whether I should preserve it as such in the EpiDoc file, or whether I should make each of these different `<change>` tags, since that's technically what they are.
Just let me know which you'd prefer, thanks!

**Comment by lcerrato** [comment]
I am going to leave these notes here but put the work on hold for now.

From the head of both files, remove resp statement as it doesn't apply. (This is only added when there is an unexpanded entity. There was no entity here and this is not always applicable in all cases.)

Change `<date>1972 (First published 1925).</date>` to `<date>1925</date>`

Remove entirely `<biblScope unit="volume">1</biblScope>`

Change `<ref target="http://www.perseus.tufts.edu/hopper/text.jsp?doc=Perseus:text:1999.01.0257">Perseus.</ref>` to
<ref target="https://catalog.hathitrust.org/Record/003443572">HathiTrust</ref>

There are entities still in the Greek file. `&gt; &quot; &apos;` etc. 
`εἰς τὸ&gt; αὐτὸς` should be `εἰς τὸ] αὐτὸς` 
`&quot;σύ should be <q>σύ</q>`
`&gt;στὶ should be ᾽στὶ`
`has supplanted the proper title of aristotle&apos;s work, which probably sas` should be
`has supplanted the proper title of Aristotle's work, which probably was`

Lots of unnecessary paragraph tags (inherited from original doc). (Some are wrong — as they appear to be lines of verse, not prose).   

Remove rend="merge" for paragraphs as this hasn't been practice until now. 

Original file has `<note n=""...>` data. Needs to be updated.

Files do not have the same number of chapters/sections 
10;82;1180 for English and 10;81;1206 for Greek. So English has one more chapter (which I think is the prologue, so that is fine) but 26 fewer sections. 

Notes have lots of typos and the tags are not meaningful. So we have italics for foreign phrases, titles, etc. 

Also check for hard breaks.

**Comment by lcerrato** [comment]
separate workflow
